name: sensor

services:
  sensor-dashboard:
    # image: sensor-dashboard-dev
    build: ../
    container_name: sensor-dashboard-dev
    ports:
      - "127.0.0.1:80:80"
    expose:
      - 80
    environment:
      - API_URL=http://sensor-webapi-dev:80
    networks:
      - sensor-network

networks:
  sensor-network:
    external: true